### ISSUE TITLE
data/marco_dev

### ISSUE THREAD

**Issue by whale-z** [ielab/CharacterBERT-DR#2]
Hi, I was wondering how you got the 6980 data in the marco_dev folder from the MS MARCO dev set?
best wishes!

**Comment by ArvinZhuang** [comment]
The original queries are downloaded from [here](https://microsoft.github.io/msmarco/Datasets) (dev small in queries.tar.gz in passage ranking dataset)

the generated typo queries and spell checker corrected queries are generated using scripts in (https://github.com/ielab/CharacterBERT-DR/tree/main/data)

**Comment by whale-z** [comment]
Thank you very much for your reply. But as far as I know, the queries.dev.tsv file under queries.tar.gz contains 101093 data, how did you filter the 6980 data out of these data? Is it just a random sampling strategy?

**Comment by ArvinZhuang** [comment]
Hi

Im sorry, the eval small queries should be in [collectionandqueries.tar.gz](https://msmarco.blob.core.windows.net/msmarcoranking/collectionandqueries.tar.gz). 
This is a sub-set of eval queries and it is used for the leaderboard eval and so in many research papers.

**Comment by whale-z** [comment]
This is exactly what I want. Thank you very much for your help.
